### ISSUE TITLE
Errors in the Website

### ISSUE THREAD

**Issue by Ashfinn** [aritra741/FindResearch.online#1]
#### Type of Error:
**Symbol Display Issue**:
   - The website doesn't show symbols in the titles properly and instead shows these:
     ```
     <math xmlns="http://www.w3.org/1998/Math/MathML" id="M1"> <mi mathvariant="script">R</mi> </math>
     ```
     ![2024-10-11 16 00 38 www findresearch online 1e29ca25caf6](https://github.com/user-attachments/assets/60de2197-fb8b-4b17-9cba-d161004fdcf8)

   - **Steps to Reproduce**:
     1. Search for "math".
     2. Filter by citations.
     3. Observe the first two results.
   - **Expected Behavior**: Symbols should be displayed correctly in the titles.
   - **Actual Behavior**: Symbols are displayed as MathML code.

2. **Citation Filtering Issue**:
   - All the articles shown have citations less than 5, even if I search with a vague keyword such as "a".
   - Filtering by citations doesn't show any articles with citations more than 0.
   - **Steps to Reproduce**:
     1. Search for a vague keyword such as "a".
     2. Filter by citations.
   - **Expected Behavior**: Articles with higher citations should be displayed when filtering by citations.
   - **Actual Behavior**: No articles with citations more than 0 are displayed.

**Comment by aritra741** [comment]
Thanks for reporting the issues!

1. It has been fixed in the latest version. Can you please confirm? 
2. We don't really have a lot of control over what is provided by the API. We can ask the API to give citation higher priority than relevance, but that compromises the quality of the results since it sometimes fetches papers with higher citations even though a paper with exact title and 0 citations might not come up.
However, I am very open to suggestions about how it can be fixed. If you have any specific plans or ideas about it, you can make those changes and create a pull request.

**Comment by Ashfinn** [comment]
The first issue is fixed. 
If I have any suggestions I would definitely tell you.. Excellent project btw.
